#!/bin/sh -e

VENDOR_ID="10c4"

get_path() {
    # List all serial device and resolve the symlinks to absolute paths
    for p in $(ls /dev/serial/by-id | xargs --no-run-if-empty -I{} readlink --canonicalize /dev/serial/by-id/{}); do
        # Their udev property are then queried and searched for the VENDOR_ID
        if [ `udevadm info -q property ${p} | grep ${VENDOR_ID} | wc -l` -gt 0 ]; then
            # If there is a match, return it.
            echo ${p}
            return 0
        fi
    done
}

# Monitor appearing/disappearing of USB devices
udevadm monitor -k -s usb | while read START OP DEV REST; do
    # Check if user defined
    RPLIDAR_AUTO_PATH="$(snapctl get serial-port)"
    # If not, look for it
    if [ -z "${RPLIDAR_AUTO_PATH}" ]; then
        if test "$START" = "KERNEL"; then
            # First lines of "udevadm monitor" output,
            # Check for already plugged devices.

            RPLIDAR_AUTO_PATH=`get_path`

        elif test "$OP" = "add"; then
            # New device got added
            RPLIDAR_AUTO_PATH=`get_path`
        fi
    fi

    if [ ${RPLIDAR_AUTO_PATH} ]; then
        logger -t ${SNAP_NAME} "Found sensor at '${RPLIDAR_AUTO_PATH}'. Launching."
        # Start rplidar
        # Sourcing so that var 'RPLIDAR_AUTO_PATH' is forwarded,
        # but in a subshell so that nothing is modified in the parent shell
        ( . $SNAP/usr/bin/launcher )
    fi
done
