name: rplidar
adopt-info: rplidar
license: BSD-2-Clause
summary: The ROS 2 rplidar snap
description: |
  ROS 2 node for SLAMTEC LIDAR.

  Upon installation, the snap must be configured:

    sudo snap set model="<lidar model>"
    sudo snap set baudrate="<baudrate>"

  Furthermore its interfaces must be connected:

    sudo snap connect rplidar:raw-usb
    sudo snap connect rplidar:ros-humble ros-humble-ros-base

  Once the snap is configured and connected,
  it automatically start and launches the driver.

grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

contact: todo
issues: todo
website: http://www.slamtec.com/en/Lidar

parts:
  rplidar:
    plugin: colcon
    colcon-cmake-args:
      - -DCMAKE_BUILD_TYPE=Release
    source: https://github.com/Slamtec/sllidar_ros2.git
    override-pull: |
        craftctl default

        version="$(grep -oP '(?<=<version>).*?(?=</version>)' $CRAFT_PART_SRC_WORK/package.xml)"
        craftctl set version="$version"

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  rplidar:
    command: usr/bin/launcher.sh
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind, raw-usb]
    extensions: [ros2-humble-ros-base]
